Hospital.Web/Areas/Admin/Controllers/ContactsController.cs
using Hospital.Services;
using Hospital.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Hospital.Web.Areas.Admin.Controllers;

[Area("admin")]
public class ContactsController : Controller
{
    private IContactService _contact;
    private IHospitalInfo _hospitalInfo;

    public ContactsController(IContactService contact, IHospitalInfo hospitalInfo)
    {
        _contact = contact;
        _hospitalInfo = hospitalInfo;
    }
    public IActionResult Index(int pageNumber = 1, int pageSize = 10)
    {
        return View(_contact.GetAll(pageNumber, pageSize));
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(ContactViewModel contactViewModel)
    {

        _contact.InsertContact(contactViewModel);
        return RedirectToAction("Index");

    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        //ViewBag.hopital = new SelectList(_hospitalInfo.GetAll(), "Id", "Name");
        //var viewModel = _contact.GetContactById(id);

        //return View(viewModel);

        var contact = _contact.GetContactById(id);

        return View(contact);
    }
    [HttpPost]
    public IActionResult Edit(ContactViewModel contactViewModel)
    {

        _contact.UpdateContact(contactViewModel);
        return RedirectToAction("Index");

    }

    public IActionResult Delete(int id)
    {
        _contact.DeleteContact(id);
        return RedirectToAction("Index");

    }
}

Hospital.Web/Areas/Admin/Views/Contacts/Create.cshtml
@model Hospital.ViewModels.ContactViewModel


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ContactViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HospitalInfoId" class="control-label"></label>
                <input asp-for="HospitalInfoId" class="form-control" />
                <span asp-validation-for="HospitalInfoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Hospital.Web/Areas/Admin/Views/Contacts/Edit.cshtml
@model Hospital.ViewModels.ContactViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ContactViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HospitalInfoId" class="control-label"></label>
                <input asp-for="HospitalInfoId" class="form-control" />
                <span asp-validation-for="HospitalInfoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Hospital.Web/Areas/Admin/Views/Contacts/Index.cshtml
@using hospitals.Utilities

@model PagedResult<Hospital.ViewModels.ContactViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Email
            </th>
            <th>
                Phone
            </th>
            <th>
                Hospital
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Data) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HospitalInfo.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>


<cs-pager cs-paging-pagesize=(int)Model.PageSize
          cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-pagenumber-patam="pageNumber"
          asp-controller="Contacts"

          asp-action="Index"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">
</cs-pager>